### ISSUE TITLE
pdfTex can't find icons in Eclipse

### ISSUE THREAD

**Issue by maletic** [SebastianOner/TUMGAD#3]
**Describe the bug**
When compiling the final document in Eclipse, pdfTex can't find the "faviconRed.png" and the "favicon.png".

**To Reproduce**
Clone and import to Eclipse and run Tumgad.java

**Expected behavior**
Should compile the exercise and solution pdfs.

**Screenshots**
![image](https://user-images.githubusercontent.com/72401732/95099809-abf95180-0730-11eb-8fe2-397c330987ce.png)

![image](https://user-images.githubusercontent.com/72401732/95099868-be738b00-0730-11eb-8ce5-59462756ef24.png)

**Desktop (please complete the following information):**
 - IDE Eclipse
- Java 14

**Solution**
It can be fixed by adding "docs/" in front of favicon.png/faviconRed.png in ExerciseTemplate.tex/SolutionTemplate.tex:

`\includegraphics[scale=0.25]{docs/favicon.png}`

`\includegraphics[scale=0.25]{docs/faviconRed.png}`

**Comment by ossner** [comment]
By "compiling the final document" do you mean that you manually compile the tex files (e.g. via console), or the call to pdflatex that happens in the sourcecode?

**Comment by maletic** [comment]
The call that happens in the code. I got those 2 errors when executing the main method as instructed in the setup. I'm not sure if anybody else had the problem, just wanted to post the solution if somebody needed it.

**Comment by ossner** [comment]
I couldn't reproduce this. The workaround is in the issue statement. If anyone wants to reopen this issue, please add a new one and reference this one (#3)
